### ISSUE TITLE
自动更新不工作

### ISSUE THREAD

**Issue by ujmyvq1582** [sundaqiang/openwrt-packages#2]
你好，我设置的更新时间是每天晚上三点，编译固件上去测试，发现没有自动更新，手动更新正常，我看crontab里也没有添加任务，这是不是一个bug呢。

**Comment by sundaqiang** [comment]
> 你好，我设置的更新时间是每天晚上三点，编译固件上去测试，发现没有自动更新，手动更新正常，我看crontab里也没有添加任务，这是不是一个bug呢。

哈，抱歉，我自动更新还没写呢，嘿嘿！

**Comment by luodaoyi** [comment]
哈哈哈
