### ISSUE TITLE
请问这些插件有没有ipk安装包呢？

### ISSUE THREAD

**Issue by cqxxbing** [sundaqiang/openwrt-packages#3]
请问这些插件有没有ipk安装包呢？原文件不知道怎么编译成ipk包，我用的是红米2100

**Comment by cqxxbing** [comment]
已找到，很好用，谢谢！再也不用每次唤醒都要去选一遍了！

**Comment by rheatin** [comment]
> 已找到，很好用，谢谢！再也不用每次唤醒都要去选一遍了！

好兄弟，分享我一下，谢谢你~
