### ISSUE TITLE
easyupdate在immortalwrt页面显示不正常

### ISSUE THREAD

**Issue by pianranjinghong** [sundaqiang/openwrt-packages#8]
luci-app-easyupdate在immortalwrt固件中显示不正常，最上方显示TypeError L.ui is undefined，界面全英文，无法选择设置，最下方出现
500 内部服务器错误

对不起，服务器遇到未知错误。

/usr/lib/lua/luci/template.lua:97: Failed to execute template 'cbi/map'.
A runtime error occurred: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'cbi/tsection'.
A runtime error occurred: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'cbi/ucisection'.
A runtime error occurred: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'easyupdate/button'.
A runtime error occurred: [string "/usr/lib/lua/luci/view/easyupdate/button.ht..."]:1: attempt to index field 'versions' (a nil value)
stack traceback:
	[string "/usr/lib/lua/luci/view/easyupdate/button.ht..."]:1: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:97: in function 
	(tail call): ?
	/usr/lib/lua/luci/cbi.lua:257: in function 'render'
	/usr/lib/lua/luci/cbi.lua:1473: in function 'render'
	/usr/lib/lua/luci/cbi.lua:266: in function 'render_children'
	[string "/usr/lib/lua/luci/view/cbi/ucisection.htm"]:7: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:97: in function 'render'
	/usr/lib/lua/luci/dispatcher.lua:700: in function 'include'
	[string "/usr/lib/lua/luci/view/cbi/tsection.htm"]:1: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:97: in function 
	(tail call): ?
	/usr/lib/lua/luci/cbi.lua:257: in function 'render'
	/usr/lib/lua/luci/cbi.lua:266: in function 'render_children'
	[string "/usr/lib/lua/luci/view/cbi/map.htm"]:6: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:97: in function 
	(tail call): ?
	/usr/lib/lua/luci/cbi.lua:257: in function 'render'
	/usr/lib/lua/luci/cbi.lua:440: in function 'render'
	/usr/lib/lua/luci/dispatcher.lua:1483: in function '_cbi'
	/usr/lib/lua/luci/dispatcher.lua:1056: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:483: in function 
无正常的保存设置和取消按钮。

目标平台 | x86/64
固件版本 | ImmortalWrt SNAPSHOT r23138-b6716429af / LuCI Master git-22.205.58442-f2ba5c4
内核版本 | 5.10.131

麻烦有时间帮忙看看怎么修改

**Comment by sundaqiang** [comment]
> luci-app-easyupdate在immortalwrt固件中显示不正常，最上方显示TypeError L.ui is undefined，界面全英文，无法选择设置，最下方出现 500 内部服务器错误
> 
> 对不起，服务器遇到未知错误。
> 
> /usr/lib/lua/luci/template.lua:97: Failed to execute template 'cbi/map'. A runtime error occurred: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'cbi/tsection'. A runtime error occurred: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'cbi/ucisection'. A runtime error occurred: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'easyupdate/button'. A runtime error occurred: [string "/usr/lib/lua/luci/view/easyupdate/button.ht..."]:1: attempt to index field 'versions' (a nil value) stack traceback: [string "/usr/lib/lua/luci/view/easyupdate/button.ht..."]:1: in main chunk stack traceback: [C]: in function 'error' /usr/lib/lua/luci/template.lua:97: in function (tail call): ? /usr/lib/lua/luci/cbi.lua:257: in function 'render' /usr/lib/lua/luci/cbi.lua:1473: in function 'render' /usr/lib/lua/luci/cbi.lua:266: in function 'render_children' [string "/usr/lib/lua/luci/view/cbi/ucisection.htm"]:7: in main chunk stack traceback: [C]: in function 'error' /usr/lib/lua/luci/template.lua:97: in function 'render' /usr/lib/lua/luci/dispatcher.lua:700: in function 'include' [string "/usr/lib/lua/luci/view/cbi/tsection.htm"]:1: in main chunk stack traceback: [C]: in function 'error' /usr/lib/lua/luci/template.lua:97: in function (tail call): ? /usr/lib/lua/luci/cbi.lua:257: in function 'render' /usr/lib/lua/luci/cbi.lua:266: in function 'render_children' [string "/usr/lib/lua/luci/view/cbi/map.htm"]:6: in main chunk stack traceback: [C]: in function 'error' /usr/lib/lua/luci/template.lua:97: in function (tail call): ? /usr/lib/lua/luci/cbi.lua:257: in function 'render' /usr/lib/lua/luci/cbi.lua:440: in function 'render' /usr/lib/lua/luci/dispatcher.lua:1483: in function '_cbi' /usr/lib/lua/luci/dispatcher.lua:1056: in function 'dispatch' /usr/lib/lua/luci/dispatcher.lua:483: in function 无正常的保存设置和取消按钮。
> 
> 目标平台 | x86/64 固件版本 | ImmortalWrt SNAPSHOT r23138-b6716429af / LuCI Master git-22.205.58442-f2ba5c4 内核版本 | 5.10.131
> 
> 麻烦有时间帮忙看看怎么修改

这个插件只适配了lede
https://github.com/coolsnowwolf/lede
自己没用过也不太想用其他版本的openwrt。所以估计是没法去修复了。抱歉！

**Comment by pianranjinghong** [comment]
好的，谢谢
